
name: 'jaffle_shop_warehouse'
version: '1.0.0'
config-version: 2

profile: 'azure-databricks-workspace-http'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

models:
    jaffle_shop_warehouse:
        materialized: table
        example:
            materialized: view
        staging:
            materialized: view
            tags: ["staging", "hourly"]

seeds:
    jaffle_shop_warehouse:
        +enabled: true
        +quote_columns: true
        +schema: seed
        raw_orders:
            +column_types:
                id: string
                user_id: string
                order_date: string
                status: string
